name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node:
          # This package supports npm v7+. While Node.js v14 should be supported
          # (with npm updated to v7+), this isn’t easy to test in GitHub Actions
          # CI as actions/setup-node@v3 doesn’t allow the npm version to be
          # configured, see:
          # https://github.com/actions/setup-node/issues/213
          # - "14"
          - "16"
          - "18"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: npm install-test
